### PR TITLE
[feat] Increase/decrease gaps/margins

### PR DESCRIPTION
**Pull request by GitSquared**
Related: #60

- `Meta+Shift+[-/=]`: Increase/decrease gaps
- `Meta+Ctrl+[-/=]`: Increase/decrease margins
- `Meta+Ctrl+Shift+-`: Reset gaps and margins to settings values

New settings:

- `gapStepSize` defaults `5`
- `marginStepSize` defaults `5`

...complete with settings UI.

### CODE REVIEW

**Comment by lingtjien** [comment]
Thank you for your commits and taking so much interest in my little project. Personally, I don't see a use case for having dynamic gaps and margins in regular work flows, so I don't think the amount of extra code is worth it, sorry.

With the exception of toggling the gaps on and off by a global shortcut, which was suggested by one of the issues so I think I may take some inspiration from your code for that.

Personally I don't even think margins are that useful, I made them originally because I used a different method to get the size of a screen which would not take into account panels and docks so I needed the margins to not have the clients tile over/under my docks/panels. But now that I use the other method which does take it into account, I think the current implementation of margins is kinda useless...

**Comment by GitSquared** [comment]
Cheers. I needed to change some things for this plugin to be compatible with my workflow and I thought I might as well share with upstream.

Regarding margins, I agree this is more of a cosmetic feature. Personally, outer  margins let me drag n drop files from my desktop, and gaps serve to visually divide borderless terminal windows.

Toggling gaps and/or margins on/off sounds like it could be useful. Looking forward to it.

**Comment by lingtjien** [comment]
You're always free to share your changes, I do however not tend to merge many things since I'm quite picky, but that does not mean that I don't look at them :)

As for your workflow regarding adding things to the desktop, what about holding the file that you want to drag and drop and then hit the global shortcut that minimizes the whole virtual desktop? (Personally, I do not use the desktop to store things so I've never tried it)

**Comment by GitSquared** [comment]
Sure, it's your call.

Minimizing shortcut might work too, I guess.

**Pull request closed without merging**
