### PR TITLE
Add option to not add new client to previous desktop

### PR DESCRIPTION
**Pull request by echo511**
Hi,
super useful script but I really don't like the default behavior where new clients are pushed to some "free" desktop.

This adds opt-out option in the config. Wording could be better so if you consider merging feel free to rephrase. Thanks.

### CODE REVIEW

**Comment by echo511** [comment]
Not that easy. Will implement client count for desktop so new clients are pushed to already created but empty desktops as well.

**Comment by lingtjien** [comment]
Your implementation has one problem, when you start adding clients only starting from the current one then you also need to loop back and check the ones before the current one as well. Else you might end up in a situation where you can't add to the ones after the current one if they're full and you will start floating clients unwillingly, while you still have space in the desktops that came before the current one.

Nonetheless, I like the idea of starting to add new clients based on the current one and then loop back and check from zero to the current again. But I would rather have that as the new default behavior as that behavior makes more sense.

I will make an example later

**Comment by echo511** [comment]
Actually the behavior you described (floating windows even if space is available before) is the intended one. It was the only think I disliked about your implementation.

I want to setup my desktop so - for example - my first has only a browser, second two terminals, ... and I do not want other windows to chaotically appear on desktops I have already set up. So I have like 10 desktops and multiple activities for my workflow and if windows start floating, good I move it myself, add a desktop etc.

**Comment by lingtjien** [comment]
What is the grid settings you use (`rows` and `columns`)? It sounds like you want your browser to always fill the whole desktop, so then why not set your browser to `minSpace` of 1, that way it will fill a desktop and nothing else can be put on that desktop because it's full.

**Comment by lingtjien** [comment]
I have a hard time trying to understand your workflow, so...

You have 3 virtual desktops in which you have open clients:

1. only browser
2. 2 terminals?
3. only writer

and you want to be able to open a browser when you're on desktop 3 with your writer to quickly look up something and then close the browser again? Something like that?

**Comment by echo511** [comment]
Sorry. The point is that if you have 20-30 windows opened and you have space left on some desktops, you might prefer **new windows not to open chaotically on previous desktops just because there is some space left**.

**Comment by lingtjien** [comment]
Hmm, I don't know, this is a tough one. 

A question: why is opening new clients on previous desktops more chaotic to you than opening on the next one?

**Comment by teonnik** [comment]
> Hmm, I don't know, this is a tough one.
> A question: why is opening new clients on previous desktops more chaotic to you than opening on the > next one?

If you don't mind me chiming in, I relate to @echo511 's experience and would definitely like to be able to opt out of the default behavior when a desktop is full. Placing a window on the next free desktop is quite disruptive to my workflow. 

The issue is that sometimes I forget that all the window slots are taken, when I open an application, I would rather see it floating on the current desktop than have me transported to some random desktop with a free slot for the window. Often when I open a new window, I may use some information present on another window in the same desktop. If I am taken away from my current desktop because there weren't any slots available, then the new window is essentially useless to me. Instead, if the window floats on my current desktop, I have a choice as to what can be done with it: I can keep it just do some quick and dirty work, I can close another window and tile the floating one... etc. 

Moreover, when moving a window from one desktop to another, if the target desktop is full, I would prefer the window to float (or at least we need to have an option for that) rather than go to the next desktop with a free slot.

**Comment by echo511** [comment]
@lingtjien To answer your question why is it more chaotic. My desktops are objective specific. On one is essay, on other I browse or play chess or whatever. If I open a notebook to write some notes about the essay I find it chaotic if it opens on the desktop where I play chess. Do you understand now what is missing for me and @teonnik and possible others?

@teonnik :) After some messing around with my modification I've arrived to the same conclusion as you and so this PR is for me outdated / not-complete.

Of course I don't know the script well enough to quickly implement the behavior below so I am currently using this modification which is decent enough for me for now. If times allow I will implement the desired and open another PR.

## The behavior I desire
- if space on current desktop -> tile new window there
- if not -> float new window there but mark as *implicit float*
- when moving window check for space on the target desktop
   - if there is space
     - if implicit float -> tile that window
     - if explicit float -> keep floatting
   - if not float but mark as implicit float
- if trying to tile explicit float on full desktop -> show some notif

Explicit float = user marked the window to float via shortcut
Implicit float = internals of the script; the window should not be floating if possible

**Comment by lingtjien** [comment]
So to answer my question, it is equally undesired to open new clients on desktops next or previous to the current one.

You would like an option to only open them on the current one (or the target for moving) and if not enough space is available to fall back to float instead of tiling to the next/previous available one?

**Comment by echo511** [comment]
@teonnik note: You can set grid space much larger than you typically use. I want 3 tiles per desktop but I configured 5. On each desktop I have a panel with task manager showing only windows from that desktop (on each monitor separate panel and separate task manager). That way I can minimize what I don't need and the script behaves very closely to what I have described above in "Desired behavior". Quick and Dirty but works ok.

**Pull request closed without merging**
