### PR TITLE
Port away from desktop file for metadata, use new config module loading mechanism

### PR DESCRIPTION
**Pull request by alex1701c**
This way we do not need to do the desktop to json conversion at runtime.

By defining the X-KDE-ConfigModule key, we no longer need to install a symlink. This is supported since KDE frameworks 5.89.

Relates to https://phabricator.kde.org/T14558

### CODE REVIEW

**Comment by lingtjien** [comment]
I was preparing to merge in your request, but when I checked out your changes and gave it a quick test, I couldn't get it to work. I did the following:

1. Delete my currently installed version of Grid-Tiling
2. Checked out your changes into a different branch
3. Run `kpackagetool5 --type KWin/Script -i *path*`
4. After successfull installation kwin already shows the script as active, but it isn't working

I've tried a few reboots between the steps, but to not avail. I also tried to check the log, but normally on Wayland I use the log file `~/.local/share/sddm/wayland-session.log` but that one seems to stay empty nowadays, so I couldn't really debug either because I don't know where logging is written too (also checked `journalctl` but that didn't give me anything either). But the log file problem is unrelated to your pull request I think.

Anything I'm doing wrong? Also do you happen to know where I can find the log of the kwin scripts in a wayland session nowadays?

**Comment by lingtjien** [comment]
Also on a side note, I made this bug request a long time ago to address this issue that you seem to have fixed. https://bugs.kde.org/show_bug.cgi?id=386509 so I guess you could close this one now

**Comment by alex1701c** [comment]
>Also on a side note, I made this bug report a long time ago to address this issue, that you seem to have fixed.

Fixed in the sense of just using X-KDE-ConfigModule which does not require copying this file?

>which would be an indication that the script is not started perhaps? Does it work fine for you now?

It seems like another key I though was unused is internally used by KWin, does it work now?

**Comment by lingtjien** [comment]
I checked your changes but there were still a few errors. I checked the documentation and I think you forgot the `"X-KDE-ConfigModule": "kwin/effects/configs/kcm_kwin4_genericscripted"` as described by https://develop.kde.org/docs/extend/plasma/kwin/#configuration . So I added that and a few other things for cleanup and it seems to work fine now 😄 

Thank you for pointing this out to me, I tested and merged your changes with my additional changes.

**Comment by alex1701c** [comment]
>I checked your changes but there were still a few errors. I checked the documentation and I think you forgot the

Darn, when re-running the desktoptojson the change was overriden and I forgot to revert the deletion of this line, sorry. But as you can see in https://github.com/lingtjien/Grid-Tiling-Kwin/commit/12ec3fb427989204619a204846a4612c246b0a50#diff-12e598daecade60b04e493f45c134fec9287ac7471114d95d1995b4fb651a6c8R20, it was there in the first state of the MR  :D

**Pull request closed without merging**
